### ISSUE TITLE
US023 - Eu como administrador desejo adicionar um novo produto de modo que fique disponível para compra

### ISSUE THREAD

**Issue by guilacerda** [Desenho-1-2018-G-6/mamid#10]
#### _**Tasks**_

- [x] . Criar campos para inserção de informações.

- [x] . Disponibilizar o produto para que possa ser criado.

 #### Critérios de Aceitação

- [x] . O administrador deve ser capaz de adicionar novo produto ao site.

- [x] . O código adicionado deve ser testado.
