### ISSUE TITLE
US01 - Eu como usuário desejo cadastrar-me no site de modo que possa me logar no site.

### ISSUE THREAD

**Issue by guilacerda** [Desenho-1-2018-G-6/mamid#4]
#### _**Tasks**_

- [x] . Criar campos para inserção de dados.

- [x] . Validar dados cadastrados.

#### Critérios de Aceitação

- [ ] . Criptografia da senha.

- [x] . O usuário deve ser capaz de se cadastrar no site.
