### ISSUE TITLE
US02- Eu como usuário desejo realizar login de modo que tenha acesso ao restante das funcionalidades do site.

### ISSUE THREAD

**Issue by guilacerda** [Desenho-1-2018-G-6/mamid#5]
#### _**Tasks**_

- [x] . Criar campos para inserção de dados.

- [x] . Validar dados inseridos com do banco de dados.

- [ ] . Redirecionar o usuário para a página inicial.

 #### Critérios de Aceitação

- [x] . O usuário deve ser capaz de logar no site.

- [ ] . O código adicionado deve ser testado.
